# Generated by Django 2.1.7 on 2019-04-27 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_info.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal_Management',
            fields=[
                ('id', models.UUIDField(default=user_info.models.generateUUID, editable=False, primary_key=True, serialize=False)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField(default=0)),
                ('cnic_no', models.IntegerField(default=0)),
                ('role', models.CharField(choices=[('USER', 'user'), ('VENDOR', 'vendor')], max_length=15)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
