# Generated by Django 2.1.7 on 2019-04-27 16:02

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal_management',
            name='cnic_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='portal_management',
            name='phone_no',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
