# Generated by Django 2.1.7 on 2019-04-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_auto_20190428_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal_management',
            name='role',
            field=models.CharField(choices=[('USER', 'user'), ('ADMIN', 'admin')], max_length=15),
        ),
    ]
