# Generated by Django 2.1.7 on 2019-04-28 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0006_auto_20190428_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal_management',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
