# Generated by Django 2.1.7 on 2019-04-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0009_patient_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_register',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
