# Generated by Django 2.1.7 on 2019-04-30 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0011_auto_20190430_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_register',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='portal_management',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
