# Generated by Django 2.1.7 on 2019-05-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0012_auto_20190430_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal_management',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
