# Generated by Django 2.1.7 on 2019-05-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0013_auto_20190517_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal_management',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
