# Generated by Django 2.1.7 on 2019-05-18 08:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0016_auto_20190518_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal_management',
            name='pic',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/uploads/photos'), upload_to=''),
        ),
    ]
