# Generated by Django 2.1.7 on 2019-05-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0017_auto_20190518_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal_management',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
